name: Catalog Service

on:
  push:
    paths:
        - catalog-service/**
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./catalog-service
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw -ntp verify

      # See https://github.com/docker/login-action
      # Only run this step on the main branch
      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Only run this step on the main branch
      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build and push Docker image
        run:
          ./mvnw spring-boot:build-image -DskipTests
          docker push ${{ vars.DOCKERHUB_USERNAME }}/bookstore-catalog-service:latest
